version: "3.9"

services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=devo_network
      - POSTGRES_USER=devonetwork
      - POSTGRES_PASSWORD=Abc123@#$

  rabbitmq:
    image: "rabbitmq:alpine"

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - celery
    restart: on-failure

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A devo_network.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  beats:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A devo_network.tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - .:/app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - .:/app